import type { ConnectionFormFieldDefinition } from '@nexql/core/core/types/connectionForm';

/**
 * PostgreSQL connection form field definitions.
 * Defines the fields shown in the connection dialog for PostgreSQL databases.
 */
export const postgresConnectionFormFields: ConnectionFormFieldDefinition[] = [
  // Basic connection fields
  {
    id: 'host',
    label: 'Host',
    type: 'text',
    placeholder: 'localhost',
    required: true,
    defaultValue: 'localhost',
    group: 'basic',
  },
  {
    id: 'port',
    label: 'Port',
    type: 'number',
    placeholder: '5432',
    required: true,
    defaultValue: 5432,
    group: 'basic',
  },
  {
    id: 'database',
    label: 'Database',
    type: 'text',
    placeholder: 'postgres',
    required: true,
    defaultValue: 'postgres',
    group: 'basic',
  },
  {
    id: 'username',
    label: 'Username',
    type: 'text',
    placeholder: 'postgres',
    required: true,
    defaultValue: 'postgres',
    group: 'basic',
  },
  {
    id: 'password',
    label: 'Password',
    type: 'password',
    placeholder: 'Enter password',
    required: false,
    group: 'basic',
  },
  // SSL fields
  {
    id: 'sslmode',
    label: 'SSL Mode',
    type: 'select',
    required: false,
    defaultValue: 'prefer',
    options: [
      { label: 'Disable', value: 'disable' },
      { label: 'Allow', value: 'allow' },
      { label: 'Prefer', value: 'prefer' },
      { label: 'Require', value: 'require' },
      { label: 'Verify CA', value: 'verify-ca' },
      { label: 'Verify Full', value: 'verify-full' },
    ],
    group: 'ssl',
  },
  {
    id: 'sslCertPath',
    label: 'Client Certificate',
    type: 'file',
    placeholder: 'Path to client certificate',
    required: false,
    helpText: 'Path to the client SSL certificate file (.crt)',
    group: 'ssl',
  },
  {
    id: 'sslKeyPath',
    label: 'Client Key',
    type: 'file',
    placeholder: 'Path to client key',
    required: false,
    helpText: 'Path to the client SSL private key file (.key)',
    group: 'ssl',
  },
  {
    id: 'sslRootCertPath',
    label: 'CA Certificate',
    type: 'file',
    placeholder: 'Path to CA certificate',
    required: false,
    helpText: 'Path to the root CA certificate file for server verification',
    group: 'ssl',
  },
  // SSH Tunnel fields
  {
    id: 'ssh.enabled',
    label: 'Enable SSH Tunnel',
    type: 'checkbox',
    required: false,
    defaultValue: false,
    group: 'ssh',
  },
  {
    id: 'ssh.host',
    label: 'SSH Host',
    type: 'text',
    placeholder: 'ssh.example.com',
    required: false,
    group: 'ssh',
  },
  {
    id: 'ssh.port',
    label: 'SSH Port',
    type: 'number',
    placeholder: '22',
    required: false,
    defaultValue: 22,
    group: 'ssh',
  },
  {
    id: 'ssh.username',
    label: 'SSH Username',
    type: 'text',
    placeholder: 'Enter SSH username',
    required: false,
    group: 'ssh',
  },
  {
    id: 'ssh.privateKeyPath',
    label: 'SSH Private Key',
    type: 'file',
    placeholder: 'Path to private key',
    required: false,
    helpText: 'Path to the SSH private key file (e.g., ~/.ssh/id_rsa)',
    group: 'ssh',
  },
  // Advanced fields
  {
    id: 'applicationName',
    label: 'Application Name',
    type: 'text',
    placeholder: 'NexQL',
    required: false,
    defaultValue: 'NexQL',
    helpText: 'Shown in pg_stat_activity',
    group: 'advanced',
  },
  {
    id: 'connectTimeout',
    label: 'Connection Timeout (s)',
    type: 'number',
    placeholder: '15',
    required: false,
    defaultValue: 15,
    helpText: 'Connection timeout in seconds',
    group: 'advanced',
  },
  {
    id: 'statementTimeout',
    label: 'Statement Timeout (ms)',
    type: 'number',
    placeholder: '0 (no timeout)',
    required: false,
    defaultValue: 0,
    helpText: 'Statement timeout in milliseconds (0 = no timeout)',
    group: 'advanced',
  },
];
